name: Release - Hugging Face Model Cards
run-name: Release - Hugging Face Model Cards

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
      inputs:
          release_commit_message:
            required: false
            type: string
            description: (Optional) Commit Message
  # Allows this workflow to be called from other workflows
  workflow_call:
      inputs:
          release_commit_message:
            required: false
            type: string
            description: (Optional) Commit Message
          skip_approval:
            required: false
            type: boolean
            default: false

jobs:
  approve:
    if: ${{ !inputs.skip_approval }}
    name: Approve Release
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: release
    steps:
      - run: echo "Release approved"

  release_huggingface:
      name: Release HuggingFace Model Cards
      needs: [approve]
      if: ${{ !cancelled() && (needs.approve.result == 'success' || needs.approve.result == 'skipped') }}
      runs-on: [tetra-ubuntu-2204, self-hosted]
      env:
        QAIHM_CI: "true"
        PYTHONUNBUFFERED: 1
        VENV_PATH: build/ci-envs/release

      steps:
      - name: Verify running on a tag
        run: |
          if [[ "${{ github.ref }}" != refs/tags/* ]]; then
            echo "Error: This workflow must be run from a tag, got ${{ github.ref }}"
            exit 1
          fi

      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: CI Setup
        uses: ./.github/actions/ci-setup
        with:
          sudo-password: ${{ secrets.TETRASERVICE_PASSWORD }}

      - name: Set Commit Message
        shell: bash
        run: |
          if [ -n "${{ inputs.release_commit_message }}" ]; then
            echo "QAIHM_COMMIT_MESSAGE=${{ inputs.release_commit_message }}" >> "$GITHUB_ENV"
          else
            echo "QAIHM_COMMIT_MESSAGE=See https://github.com/qualcomm/ai-hub-models/releases/\$QAIHM_TAG for changelog." >> "$GITHUB_ENV"
          fi

      - name: Build Release Huggingface model cards
        shell: bash
        env:
          QAIHM_HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
        run:
          python3 scripts/build_and_test.py --venv="${{ env.VENV_PATH }}" release_huggingface
